services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php
    
    # Espongo porta 9000 per nginx sull'host
    ports:
      - "9000:9000"
    
    # Monto il codice come volume per sviluppo
    # Ogni modifica al codice Ã¨ immediatamente visibile
    volumes:
      - ./:/var/www/html
    
    # Riavvio automatico se il container si blocca
    restart: unless-stopped
